using System.Text;

namespace WxMonitor.Svc.Watchers;

/// <summary>Shared pieces of the plain-text alert bodies the watchers build.</summary>
internal static class AlertBody
{
    /// <summary>Horizontal rule used to frame quoted content in an alert body.</summary>
    internal const string Separator = "─────────────────────────────────────────────";

    /// <summary>Appends the standard "Generated by WxMonitor at … UTC" footer line.</summary>
    internal static void AppendFooter(StringBuilder sb, DateTime now)
        => sb.AppendLine($"Generated by WxMonitor at {now:yyyy-MM-dd HH:mm:ss} UTC");
}