using System.Text;

using MetarParser.Data;

using Microsoft.EntityFrameworkCore;

namespace WxMonitor.Svc.Watchers;

/// <summary>
/// Queries the database for the most recent METAR observation and raises a (global) finding when
/// it is older than the configured staleness threshold — a sign that WxParser.Svc has stopped
/// ingesting, or the upstream METAR API is unreachable. Disabled when the threshold is not positive.
/// </summary>
public sealed class MetarStalenessWatcher : IWatcher
{
    /// <inheritdoc/>
    public string Id => "metar-staleness";

    /// <inheritdoc/>
    public string DisplayName => "METAR Staleness";

    /// <inheritdoc/>
    public async Task<IReadOnlyList<Finding>> RunAsync(WatcherContext ctx, CancellationToken ct)
    {
        if (ctx.Config.MetarStalenessThresholdMinutes <= 0)
            return [];

        await using var db = new WeatherDataContext(ctx.DbOptions);
        var mostRecentObsUtc = await db.Metars.MaxAsync(m => (DateTime?)m.ObservationUtc, ct);

        var ageMinutes = mostRecentObsUtc.HasValue
            ? (ctx.UtcNow - mostRecentObsUtc.Value).TotalMinutes
            : double.MaxValue;

        if (ageMinutes <= ctx.Config.MetarStalenessThresholdMinutes)
            return [];

        return
        [
            new Finding(
                Id,
                "[WxMonitor] METAR data is stale — no recent observations",
                BuildBody(mostRecentObsUtc, ctx.Config.MetarStalenessThresholdMinutes, ctx.UtcNow),
                new CooldownSlot(
                    () => ctx.State.LastMetarStalenessAlertSentUtc,
                    v => { ctx.State.LastMetarStalenessAlertSentUtc = v; ctx.MarkStateDirty(); })),
        ];
    }

    /// <summary>Builds the plain-text alert body explaining that no recent METAR observations were found.</summary>
    private static string BuildBody(DateTime? mostRecentUtc, int thresholdMinutes, DateTime now)
    {
        var sb = new StringBuilder();
        sb.AppendLine("WxMonitor detected stale METAR data in the database.");
        sb.AppendLine();
        if (mostRecentUtc.HasValue)
        {
            var age = now - mostRecentUtc.Value;
            sb.AppendLine($"  Most recent observation: {mostRecentUtc.Value:yyyy-MM-dd HH:mm} UTC  ({(int)age.TotalMinutes} minute(s) ago)");
        }
        else
        {
            sb.AppendLine("  No METAR observations found in the database at all.");
        }
        sb.AppendLine($"  Staleness threshold:     {thresholdMinutes} minute(s)");
        sb.AppendLine();
        sb.AppendLine("This may indicate WxParser.Svc is not running, or the AWC METAR API is unreachable.");
        sb.AppendLine("Check the WxParser.Svc log and Windows Service Manager for details.");
        sb.AppendLine();
        sb.AppendLine($"Generated by WxMonitor at {now:yyyy-MM-dd HH:mm:ss} UTC");
        return sb.ToString();
    }
}