using System.Net.Http.Json;
using System.Text.Json;
using System.Text.Json.Serialization;

using WxServices.Logging;

namespace WxReport.Svc;

/// <summary>
/// Token-usage breakdown returned by the Anthropic Messages API for a single
/// request.  Cache fields are zero when no cache hit occurred or the cache
/// markers in the request did not produce a cacheable prefix.
/// </summary>
/// <param name="InputTokens">Total billed input tokens for the request (cached and uncached combined).</param>
/// <param name="OutputTokens">Output tokens generated by the model.</param>
/// <param name="CacheReadInputTokens">Input tokens served from a prior cache write (heavily discounted).</param>
/// <param name="CacheCreationInputTokens">Input tokens written to the cache by this request (one-time write cost).</param>
public sealed record TokenUsage(
    int InputTokens,
    int OutputTokens,
    int CacheReadInputTokens,
    int CacheCreationInputTokens);

/// <summary>
/// Successful result of <see cref="ClaudeClient.InvokeReconciliationAsync"/>:
/// the raw <c>tool_use.input</c> JSON returned by Claude, plus token usage.
/// Schema validation of <see cref="ToolUseInput"/> is the caller's
/// responsibility — typically by reading <c>final_snapshot</c> as a string
/// and passing it through
/// <see cref="MetarParser.Data.Entities.ForecastSnapshotBody.Deserialize"/>,
/// which enforces both shape and the precipPhenomenon-iff-non-none invariant.
/// </summary>
/// <param name="ToolUseInput">JsonElement representing the tool_use block's <c>input</c> object.</param>
/// <param name="Tokens">Token-usage metadata extracted from the response's <c>usage</c> block.</param>
public sealed record ClaudeReconciliationResult(
    JsonElement ToolUseInput,
    TokenUsage Tokens);

/// <summary>
/// Thin wrapper around the Anthropic Messages API.  Exposes the single
/// tool-use call driving the WX-79 forecast reconciliation pass; higher-level
/// orchestration (per-recipient system-prompt construction, user-message
/// assembly, response validation) lives in <see cref="ForecastReconciler"/>.
/// </summary>
public sealed class ClaudeClient
{
    private const string MessagesEndpoint = "https://api.anthropic.com/v1/messages";
    private const string AnthropicVersion = "2023-06-01";

    private readonly HttpClient _http;
    private readonly string _apiKey;
    private readonly string _model;
    private readonly string _personaPrefix;

    /// <summary>Initializes a new instance of <see cref="ClaudeClient"/> with the given credentials, model, and persona prefix.</summary>
    /// <param name="http">HTTP client used for all requests to the Anthropic Messages API.</param>
    /// <param name="apiKey">Anthropic API key; sent as the <c>x-api-key</c> header.</param>
    /// <param name="model">Claude model ID to use for generation (e.g. <c>"claude-sonnet-4-6"</c>).</param>
    /// <param name="personaPrefix">
    /// Author-persona text (the contents of the recipient's persona file, e.g. <c>AboutPaul.md</c>)
    /// sent as the first <c>system</c> content block on every Messages API call.
    /// </param>
    public ClaudeClient(HttpClient http, string apiKey, string model, string personaPrefix)
    {
        _http = http;
        _apiKey = apiKey;
        _model = model;
        _personaPrefix = personaPrefix;
    }

    /// <summary>
    /// Invokes Claude with tool-use enabled to perform the WX-79 forecast
    /// reconciliation pass.  Builds the three-block system prompt (persona +
    /// reconciliation guidance + per-recipient rendering rules), forces the
    /// <c>submit_reconciled_report</c> tool, posts to the Anthropic Messages
    /// API with retry/backoff, and returns the raw tool_use input JSON plus
    /// token-usage metadata.  Returns <see langword="null"/> on HTTP failure,
    /// on a missing or wrong-named tool_use block, or on response-parse
    /// failure.
    ///
    /// <para>
    /// Schema validation of the returned input is the caller's responsibility:
    /// the standard path is to read <c>final_snapshot</c> as a string and pass
    /// it through <see cref="MetarParser.Data.Entities.ForecastSnapshotBody.Deserialize"/>,
    /// which enforces both shape and the precipPhenomenon-iff-non-none
    /// invariant.
    /// </para>
    /// </summary>
    /// <param name="perRecipientSystemPrompt">
    /// Per-recipient rendering rules; the third (uncached) system block.
    /// Built by the caller from language, units, change-severity, and other
    /// per-call context.
    /// </param>
    /// <param name="userMessageText">
    /// User message carrying the structured payload (provisional snapshot,
    /// observation, forecast, prior snapshot, with their timestamps).
    /// </param>
    /// <param name="ct">Cancellation token propagated to the HTTP request so that host shutdown aborts an in-flight API call.</param>
    /// <returns>The parsed tool_use input plus token usage on success; <see langword="null"/> on transport, schema, or parse failure.</returns>
    /// <sideeffects>Makes an HTTP POST request to the Anthropic Messages API. Writes error log entries on failure.</sideeffects>
    public async Task<ClaudeReconciliationResult?> InvokeReconciliationAsync(
        string perRecipientSystemPrompt,
        string userMessageText,
        CancellationToken ct = default)
    {
        var request = new
        {
            model = _model,
            max_tokens = 8192,
            system = new object[]
            {
                new { type = "text", text = _personaPrefix },
                new
                {
                    type = "text",
                    text = ReconcilerPrompts.ReconciliationGuidanceText,
                    cache_control = new { type = "ephemeral" },
                },
                new { type = "text", text = perRecipientSystemPrompt },
            },
            tools = new[] { ReconcilerPrompts.BuildSubmitReconciledReportTool() },
            tool_choice = new { type = "tool", name = "submit_reconciled_report" },
            messages = new[]
            {
                new { role = "user", content = userMessageText },
            },
        };

        const int maxAttempts = 3;
        HttpResponseMessage resp;

        for (int attempt = 1; ; attempt++)
        {
            using var req = new HttpRequestMessage(HttpMethod.Post, MessagesEndpoint);
            req.Headers.Add("x-api-key", _apiKey);
            req.Headers.Add("anthropic-version", AnthropicVersion);
            req.Content = JsonContent.Create(request);

            try
            {
                resp = await _http.SendAsync(req, ct);
            }
            catch (Exception ex) when (attempt < maxAttempts && ex is HttpRequestException)
            {
                Logger.Warn($"Claude API request failed (attempt {attempt}/{maxAttempts}): {ex.Message}");
                await Task.Delay(TimeSpan.FromSeconds(attempt * 2), ct);
                continue;
            }
            catch (Exception ex)
            {
                Logger.Error($"Claude API request failed: {ex}");
                return null;
            }

            var statusCode = (int)resp.StatusCode;
            if (resp.IsSuccessStatusCode) break;

            var body = await resp.Content.ReadAsStringAsync();
            resp.Dispose();

            if (attempt < maxAttempts && statusCode is 429 or 529 or >= 500)
            {
                Logger.Warn($"Claude API returned {statusCode} (attempt {attempt}/{maxAttempts}): {body}");
                await Task.Delay(TimeSpan.FromSeconds(attempt * 2), ct);
                continue;
            }

            Logger.Error($"Claude API returned {statusCode}: {body}");
            return null;
        }

        using (resp)
        {
            ClaudeResponse? parsed;
            try
            {
                parsed = await resp.Content.ReadFromJsonAsync<ClaudeResponse>();
            }
            catch (Exception ex)
            {
                Logger.Error($"Failed to parse Claude API response: {ex.Message}");
                return null;
            }

            var toolUse = parsed?.Content?.FirstOrDefault(
                c => c.Type == "tool_use" && c.Name == "submit_reconciled_report");

            if (toolUse is null)
            {
                Logger.Error("Claude response contained no submit_reconciled_report tool_use block.");
                return null;
            }

            var usage = parsed?.Usage;
            var tokens = new TokenUsage(
                InputTokens: usage?.InputTokens ?? 0,
                OutputTokens: usage?.OutputTokens ?? 0,
                CacheReadInputTokens: usage?.CacheReadInputTokens ?? 0,
                CacheCreationInputTokens: usage?.CacheCreationInputTokens ?? 0);

            return new ClaudeReconciliationResult(toolUse.Input, tokens);
        }
    }

    // ── response DTOs ─────────────────────────────────────────────────────────

    private sealed class ClaudeResponse
    {
        [JsonPropertyName("content")]
        public List<ContentBlock>? Content { get; set; }

        [JsonPropertyName("usage")]
        public TokenUsageDto? Usage { get; set; }
    }

    private sealed class ContentBlock
    {
        [JsonPropertyName("type")] public string? Type { get; set; }
        [JsonPropertyName("text")] public string? Text { get; set; }

        /// <summary>Tool name when <see cref="Type"/> is <c>"tool_use"</c>; <see langword="null"/> for text blocks.</summary>
        [JsonPropertyName("name")] public string? Name { get; set; }

        /// <summary>Tool-use input object when <see cref="Type"/> is <c>"tool_use"</c>; default-valued for text blocks.</summary>
        [JsonPropertyName("input")] public JsonElement Input { get; set; }
    }

    private sealed class TokenUsageDto
    {
        [JsonPropertyName("input_tokens")] public int InputTokens { get; set; }
        [JsonPropertyName("output_tokens")] public int OutputTokens { get; set; }
        [JsonPropertyName("cache_creation_input_tokens")] public int CacheCreationInputTokens { get; set; }
        [JsonPropertyName("cache_read_input_tokens")] public int CacheReadInputTokens { get; set; }
    }
}