using System.Net.Http.Json;
using System.Text.Json;
using System.Text.Json.Serialization;

using WxServices.Logging;

namespace WxReport.Svc;

/// <summary>
/// Token-usage breakdown returned by the Anthropic Messages API for a single
/// request.  Cache fields are zero when no cache hit occurred or the cache
/// markers in the request did not produce a cacheable prefix.
/// </summary>
/// <param name="InputTokens">Total billed input tokens for the request (cached and uncached combined).</param>
/// <param name="OutputTokens">Output tokens generated by the model.</param>
/// <param name="CacheReadInputTokens">Input tokens served from a prior cache write (heavily discounted).</param>
/// <param name="CacheCreationInputTokens">Input tokens written to the cache by this request (one-time write cost).</param>
public sealed record TokenUsage(
    int InputTokens,
    int OutputTokens,
    int CacheReadInputTokens,
    int CacheCreationInputTokens);

/// <summary>
/// Successful result of <see cref="ClaudeClient.InvokeReconciliationAsync"/>:
/// the raw <c>tool_use.input</c> JSON returned by Claude, plus token usage.
/// Schema validation of <see cref="ToolUseInput"/> is the caller's
/// responsibility — typically by reading <c>final_snapshot</c> as a string
/// and passing it through
/// <see cref="MetarParser.Data.Entities.ForecastSnapshotBody.Deserialize"/>,
/// which enforces both shape and the precipPhenomenon-iff-non-none invariant.
/// </summary>
/// <param name="ToolName">Name of the tool Claude invoked — <c>"submit_reconciled_report"</c> to send, or <c>"skip_send"</c> for the WX-80 "not news" outcome.</param>
/// <param name="ToolUseId">The tool_use block's <c>id</c>.  Lets the caller (WX-148) replay a rejected attempt as a <c>tool_result</c> on the next call, so a validation retry carries the specific failure back to Claude instead of blindly resampling.</param>
/// <param name="ToolUseInput">JsonElement representing the tool_use block's <c>input</c> object.</param>
/// <param name="Tokens">Token-usage metadata extracted from the response's <c>usage</c> block.</param>
/// <param name="StopReason">
/// The response's <c>stop_reason</c> (e.g. <c>"tool_use"</c>, <c>"end_turn"</c>,
/// <c>"max_tokens"</c>).  <c>"max_tokens"</c> means generation was cut at the
/// output-token cap, so <see cref="ToolUseInput"/> is a truncated partial object
/// (a trailing required field is typically missing).  The caller checks this
/// before reading fields so a truncation is reported as such rather than
/// mislabelled a missing/omitted field (WX-109).
/// </param>
public sealed record ClaudeReconciliationResult(
    string ToolName,
    string ToolUseId,
    JsonElement ToolUseInput,
    TokenUsage Tokens,
    string? StopReason);

/// <summary>
/// A rejected reconciliation attempt, replayed on the next call as the
/// assistant's <c>tool_use</c> followed by a user <c>tool_result</c> carrying the
/// validation error (WX-148).  Accumulated by <see cref="ForecastReconciler"/>
/// across attempts so each retry is a <em>continuation</em> that sees why the
/// prior attempts failed — not a blind resample.  The stable
/// system-prompt + first-user-message prefix still cache-hits; only these
/// appended turns are uncached, and only on a cycle that actually failed.
/// </summary>
/// <param name="ToolUseId">The rejected attempt's tool_use id; ties the replayed tool_use to its tool_result.</param>
/// <param name="ToolName">The tool the rejected attempt called.</param>
/// <param name="ToolUseInput">The rejected attempt's raw input, replayed verbatim so Claude sees exactly what it submitted.</param>
/// <param name="ErrorText">The validation failure, phrased as a correction instruction Claude should act on.</param>
public sealed record ReconciliationCorrection(
    string ToolUseId,
    string ToolName,
    JsonElement ToolUseInput,
    string ErrorText);

/// <summary>
/// Thin wrapper around the Anthropic Messages API.  Exposes the single
/// tool-use call driving the WX-79 forecast reconciliation pass; higher-level
/// orchestration (per-recipient system-prompt construction, user-message
/// assembly, response validation) lives in <see cref="ForecastReconciler"/>.
/// </summary>
public sealed class ClaudeClient
{
    private const string MessagesEndpoint = "https://api.anthropic.com/v1/messages";
    private const string AnthropicVersion = "2023-06-01";

    // Output-token ceiling for the reconciliation call. The four artifacts
    // (a full inline-CSS HTML email_body, a final_snapshot of up to 24 six-hour
    // blocks for a six-day horizon, the WX-128 structured_report with its
    // per-language narratives, and a reasoning_trace) are emitted in one
    // tool_use response; a truncation returns stop_reason "max_tokens" with a
    // partial tool_use input — a trailing required field is dropped and the
    // pass fails (WX-109 raised 8192→16384 for the three-artifact shape).
    // WX-128 adds the structured report — roughly an email_body's worth of
    // prose per narrative language — so the ceiling scales with the language
    // count instead of doubling unconditionally: a single-language cycle keeps
    // near the old worst-case failure cost and OTPM admission weight, and the
    // headroom grows only when WX-130's multi-language locality sets actually
    // need it. Billing is per token actually generated, not per ceiling.
    // (Streaming, WX-101, is the eventual fix for the cap-vs-timeout tension.)
    private const int BaseOutputTokens = 16384;
    private const int PerLanguageOutputTokens = 8192;

    // WX-165 pinned this to 0.25 to damp invented changes: the call authored the
    // structural changes[], and at the Anthropic default (1.0) each validation retry
    // rolled a FRESH phantom instead of converging. WX-189 moved change DETECTION out
    // of the LLM — changes[] is now computed deterministically from the snapshot — so
    // structural correctness no longer rides on sampling, and the WX-165 payoff applies:
    // raise the temperature back up so the changeSummary/closing prose breathes
    // (0.25 flattens it toward repetitive phrasing across localities and days).
    // Deliberately a MODERATE 0.5, not the old 1.0 default: final_snapshot is still
    // Claude's, and the computed change set derives from it, so we still want a
    // reasonably stable reconciled snapshot — 0.5 frees the prose without letting the
    // snapshot wander. Final value calibrated post-deploy (WX-189 §13).
    private const double ReconcilerTemperature = 0.5;

    // WX-172 template-generation call. Translation is faithful, not creative — a low
    // temperature keeps it close to the sense the context fixes rather than paraphrasing.
    // The output cap is generous because the call returns one entry per vocabulary token
    // (~100), each with a phrase, a translated context sentence, and an optional note;
    // billing is per token generated, and the call runs only when a language is enabled,
    // so headroom against truncation matters more than a tight ceiling here.
    private const double TranslatorTemperature = 0.2;
    private const int TranslationOutputTokens = 32768;

    private readonly HttpClient _http;
    private readonly string _apiKey;
    private readonly string _model;
    private readonly string _personaPrefix;

    /// <summary>Initializes a new instance of <see cref="ClaudeClient"/> with the given credentials, model, and persona prefix.</summary>
    /// <param name="http">HTTP client used for all requests to the Anthropic Messages API.</param>
    /// <param name="apiKey">Anthropic API key; sent as the <c>x-api-key</c> header.</param>
    /// <param name="model">Claude model ID to use for generation (e.g. <c>"claude-sonnet-4-6"</c>).</param>
    /// <param name="personaPrefix">
    /// Author-persona text (the contents of the recipient's persona file, e.g. <c>AboutPaul.md</c>)
    /// sent as the first <c>system</c> content block on every Messages API call.
    /// </param>
    public ClaudeClient(HttpClient http, string apiKey, string model, string personaPrefix)
    {
        _http = http;
        _apiKey = apiKey;
        _model = model;
        _personaPrefix = personaPrefix;
    }

    /// <summary>
    /// Invokes Claude with tool-use enabled to perform the WX-79 forecast
    /// reconciliation pass.  Builds the three-block system prompt (persona +
    /// reconciliation guidance + per-recipient rendering rules), offers the
    /// reconciliation tool(s) per <paramref name="allowSkip"/> (forcing
    /// <c>submit_reconciled_report</c> when <see langword="false"/>, or offering
    /// it alongside <c>skip_send</c> with <c>tool_choice: any</c> when
    /// <see langword="true"/>), posts to the Anthropic Messages API with
    /// retry/backoff, and returns the selected tool's name and raw tool_use
    /// input JSON plus token-usage metadata.  Returns <see langword="null"/> on
    /// HTTP failure, on a missing or wrong-named tool_use block, or on
    /// response-parse failure.  A host-shutdown cancellation (the request <c>ct</c>
    /// is signalled) is NOT a null case: it propagates as
    /// <see cref="OperationCanceledException"/> (WX-235).
    ///
    /// <para>
    /// Schema validation of the returned input is the caller's responsibility:
    /// the standard path is to read <c>final_snapshot</c> as a string and pass
    /// it through <see cref="MetarParser.Data.Entities.ForecastSnapshotBody.Deserialize"/>,
    /// which enforces both shape and the precipPhenomenon-iff-non-none
    /// invariant.
    /// </para>
    /// </summary>
    /// <param name="perRecipientSystemPrompt">
    /// Per-recipient rendering rules; the third (uncached) system block.
    /// Built by the caller from language, units, change-severity, and other
    /// per-call context.
    /// </param>
    /// <param name="userMessageText">
    /// User message carrying the structured payload (provisional snapshot,
    /// observation, forecast, prior snapshot, with their timestamps).
    /// </param>
    /// <param name="allowSkip">
    /// When <see langword="true"/> (unscheduled, arrival-triggered cycles), both
    /// the <c>submit_reconciled_report</c> and <c>skip_send</c> tools are offered
    /// and <c>tool_choice</c> is <c>any</c>, so Claude may decline to send.  When
    /// <see langword="false"/> (scheduled / first / startup sends), only
    /// <c>submit_reconciled_report</c> is offered and forced — those cycles are
    /// always worth sending and must never be skipped.
    /// </param>
    /// <param name="narrativeLanguages">
    /// ISO 639-1 codes the structured report's narrative must carry (WX-128);
    /// becomes the required-keys set of the tool schema's <c>narrative</c>
    /// object.  Stable per recipient/locality so the tool definition — part of
    /// the cached prompt prefix — stays byte-identical across cycles.
    /// </param>
    /// <param name="ct">Cancellation token propagated to the HTTP request so that host shutdown aborts an in-flight API call.</param>
    /// <returns>The chosen tool's name and input plus token usage on success; <see langword="null"/> on transport, schema, or parse failure. A host-shutdown cancellation (signalled <c>ct</c>) throws <see cref="OperationCanceledException"/> rather than returning null (WX-235).</returns>
    /// <sideeffects>Makes an HTTP POST request to the Anthropic Messages API. Writes error log entries on failure.</sideeffects>
    public async Task<ClaudeReconciliationResult?> InvokeReconciliationAsync(
        string perRecipientSystemPrompt,
        string userMessageText,
        bool allowSkip,
        IReadOnlyList<string> narrativeLanguages,
        IReadOnlyList<ReconciliationCorrection>? corrections = null,
        CancellationToken ct = default)
    {
        // Arrival-triggered cycles offer Claude the invalidation gate (submit OR
        // skip, tool_choice "any"); scheduled/first/startup cycles force the
        // submit tool so a guaranteed send can never be skipped.
        var tools = allowSkip
            ? new[] { ReconcilerPrompts.BuildSubmitReconciledReportTool(narrativeLanguages), ReconcilerPrompts.BuildSkipSendTool() }
            : new[] { ReconcilerPrompts.BuildSubmitReconciledReportTool(narrativeLanguages) };
        object toolChoice = allowSkip
            ? new { type = "any" }
            : new { type = "tool", name = "submit_reconciled_report" };

        var request = new
        {
            model = _model,
            max_tokens = BaseOutputTokens + PerLanguageOutputTokens * narrativeLanguages.Count,
            temperature = ReconcilerTemperature,   // WX-189: moderate, prose breathes now that detection is deterministic (see const)
            system = new object[]
            {
                new { type = "text", text = _personaPrefix },
                new
                {
                    type = "text",
                    text = ReconcilerPrompts.ReconciliationGuidanceText,
                    cache_control = new { type = "ephemeral" },
                },
                new { type = "text", text = perRecipientSystemPrompt },
            },
            tools,
            tool_choice = toolChoice,
            messages = BuildMessages(userMessageText, corrections),
        };

        // submit_reconciled_report is always permitted; skip_send only when this cycle
        // offered it (allowSkip). The set membership is what SendForToolUseAsync enforces
        // at the API boundary, so a skip_send returned on a guaranteed send is rejected.
        var permittedTools = allowSkip
            ? new HashSet<string>(StringComparer.Ordinal) { "submit_reconciled_report", "skip_send" }
            : new HashSet<string>(StringComparer.Ordinal) { "submit_reconciled_report" };
        return await SendForToolUseAsync(request, permittedTools, ct);
    }

    /// <summary>
    /// Posts a fully-built Messages API request (with retry/backoff on transient
    /// transport and 429/5xx) and returns its single <c>tool_use</c> block as a
    /// <see cref="ClaudeReconciliationResult"/>, or <see langword="null"/> on transport
    /// failure, a parse failure, a response that is not exactly one tool_use block, a
    /// tool not in <paramref name="permittedTools"/>, or a tool_use missing its id.
    /// Shared by the reconciliation (<see cref="InvokeReconciliationAsync"/>) and
    /// translation (<see cref="InvokeTranslationAsync"/>) calls — the request shape and
    /// permitted-tool set differ, the POST/parse contract does not.
    /// <para>
    /// A host-shutdown cancellation (the request <c>ct</c> is signalled) is NOT one of the <see langword="null"/>
    /// cases above — it propagates as <see cref="OperationCanceledException"/> so callers can distinguish a
    /// clean shutdown from a genuine failure (WX-235).
    /// </para>
    /// </summary>
    private async Task<ClaudeReconciliationResult?> SendForToolUseAsync(
        object request, IReadOnlySet<string> permittedTools, CancellationToken ct)
    {
        const int maxAttempts = 3;
        HttpResponseMessage resp;

        for (int attempt = 1; ; attempt++)
        {
            using var req = new HttpRequestMessage(HttpMethod.Post, MessagesEndpoint);
            req.Headers.Add("x-api-key", _apiKey);
            req.Headers.Add("anthropic-version", AnthropicVersion);
            req.Content = JsonContent.Create(request);

            try
            {
                resp = await _http.SendAsync(req, ct);
            }
            catch (OperationCanceledException) when (ct.IsCancellationRequested)
            {
                // Genuine host-shutdown cancellation — abort promptly, do not retry, and PROPAGATE it. A
                // swallowed null here is indistinguishable from a real Claude failure: it surfaces as a
                // spurious "reconciliation failed" on the report cycle (WX-100 returned null) and, worse, lets
                // the QA-rerun worker mark a shutdown-interrupted run Succeeded over an empty package (WX-235
                // step 9). Propagating lets the worker release its claim and re-run on restart, and lets the
                // report cycle's stoppingToken-filtered catches unwind quietly.
                Logger.Info("Claude API request canceled by host shutdown.");
                throw;
            }
            catch (Exception ex) when (attempt < maxAttempts && ex is HttpRequestException)
            {
                // Connection-level failures are transient — retry with backoff.
                Logger.Warn($"Claude API request failed (attempt {attempt}/{maxAttempts}): {ex.Message}");
                await Task.Delay(TimeSpan.FromSeconds(attempt * 2), ct);
                continue;
            }
            catch (Exception ex)
            {
                // Includes an HttpClient.Timeout (TaskCanceledException, ct not
                // signalled).  WX-100: the dedicated Claude client's generous timeout
                // makes timeouts rare, and a timeout at that ceiling signals a real
                // stall, not a blip — so fail the pass and recover next cycle rather
                // than retrying a multi-minute call up to 3x (code-review finding).
                Logger.Error($"Claude API request failed: {ex}");
                return null;
            }

            var statusCode = (int)resp.StatusCode;
            if (resp.IsSuccessStatusCode) break;

            var body = await resp.Content.ReadAsStringAsync();
            resp.Dispose();

            if (attempt < maxAttempts && statusCode is 429 or 529 or >= 500)
            {
                Logger.Warn($"Claude API returned {statusCode} (attempt {attempt}/{maxAttempts}): {body}");
                await Task.Delay(TimeSpan.FromSeconds(attempt * 2), ct);
                continue;
            }

            Logger.Error($"Claude API returned {statusCode}: {body}");
            return null;
        }

        using (resp)
        {
            ClaudeResponse? parsed;
            try
            {
                parsed = await resp.Content.ReadFromJsonAsync<ClaudeResponse>();
            }
            catch (Exception ex)
            {
                Logger.Error($"Failed to parse Claude API response: {ex.Message}");
                return null;
            }

            // Enforce the tool contract on the way back: a valid response is exactly one
            // tool_use block whose name is in permittedTools. Anything else — zero blocks,
            // more than one block (a self-contradictory pair would otherwise be resolved by
            // arbitrary ordering), or an un-offered tool (e.g. a skip_send returned on a
            // guaranteed send, where the caller passed only submit_reconciled_report) — is
            // malformed output: reject it here at the API boundary (return null -> caller's
            // failure path) rather than guess. This keeps the choice deterministic and makes
            // ClaudeReconciliationResult.ToolName always a tool the caller actually offered.
            var toolUseBlocks = parsed?.Content?.Where(c => c.Type == "tool_use").ToList();

            if (toolUseBlocks is not { Count: 1 })
            {
                // Include stop_reason: a "max_tokens" truncation can cut generation
                // before any tool_use block is emitted, which would otherwise read as
                // a baffling "0 tool_use blocks" rather than the token-cap hit it is
                // (WX-109). The common truncation case — one block with a partial
                // input — is handled downstream in ForecastReconciler via StopReason.
                Logger.Error($"Claude response had {toolUseBlocks?.Count ?? 0} tool_use block(s); expected exactly 1 (permitted=[{string.Join(", ", permittedTools)}], stop_reason={parsed?.StopReason ?? "null"}).");
                return null;
            }

            var toolName = toolUseBlocks[0].Name;
            if (toolName is null || !permittedTools.Contains(toolName))
            {
                Logger.Error($"Claude response tool_use '{toolName ?? "(none)"}' is not one of the permitted tools [{string.Join(", ", permittedTools)}].");
                return null;
            }

            var toolUse = toolUseBlocks[0];

            // A tool_use block without an id is malformed (the API always assigns one);
            // treat it as such rather than substituting an empty id, which would later
            // produce a tool_use/tool_result pair the retry can't match (WX-148 feedback).
            if (string.IsNullOrEmpty(toolUse.Id))
            {
                Logger.Error($"Claude response tool_use '{toolName}' is missing its id.");
                return null;
            }

            var usage = parsed?.Usage;
            var tokens = new TokenUsage(
                InputTokens: usage?.InputTokens ?? 0,
                OutputTokens: usage?.OutputTokens ?? 0,
                CacheReadInputTokens: usage?.CacheReadInputTokens ?? 0,
                CacheCreationInputTokens: usage?.CacheCreationInputTokens ?? 0);

            return new ClaudeReconciliationResult(toolName, toolUse.Id, toolUse.Input, tokens, parsed?.StopReason);
        }
    }

    /// <summary>
    /// Invokes Claude to translate the baseline report vocabulary into one target
    /// language (WX-172).  Builds the two-block request (the cached translation
    /// guidance system block + the user message carrying the target language and the
    /// token list), forces the <c>translate_templates</c> tool, and returns its raw
    /// tool_use input — an object with <c>cultureName</c> and a <c>translations</c>
    /// array.  Validation of that input (same token set, placeholders preserved,
    /// length/char hygiene, representability) is the caller's responsibility
    /// (<see cref="TemplateTranslator"/>), which replays a rejected attempt via
    /// <paramref name="corrections"/> exactly as the reconciler does.
    /// </summary>
    /// <param name="userMessageText">The user message: the target language name plus the JSON token list (token, englishPhrase, context, contextKind) to translate.</param>
    /// <param name="corrections">Rejected prior attempts replayed as tool_use + tool_result so a validation retry carries its feedback to Claude; <see langword="null"/> on the first attempt.</param>
    /// <param name="ct">Cancellation token propagated to the HTTP request so host shutdown aborts an in-flight call.</param>
    /// <returns>The <c>translate_templates</c> tool's input plus token usage on success; <see langword="null"/> on transport, schema, or parse failure. A host-shutdown cancellation (signalled <c>ct</c>) throws <see cref="OperationCanceledException"/> rather than returning null (WX-235).</returns>
    /// <sideeffects>Makes an HTTP POST request to the Anthropic Messages API. Writes error log entries on failure.</sideeffects>
    public async Task<ClaudeReconciliationResult?> InvokeTranslationAsync(
        string userMessageText,
        IReadOnlyList<ReconciliationCorrection>? corrections = null,
        CancellationToken ct = default)
    {
        var request = new
        {
            model = _model,
            max_tokens = TranslationOutputTokens,
            temperature = TranslatorTemperature,
            // No persona and no per-recipient block: translation authors fixed vocabulary,
            // not a report in Paul's voice. Just the cached guidance block.
            system = new object[]
            {
                new
                {
                    type = "text",
                    text = TranslatorPrompts.TranslationGuidanceText,
                    cache_control = new { type = "ephemeral" },
                },
            },
            tools = new[] { TranslatorPrompts.BuildTranslateTemplatesTool() },
            tool_choice = new { type = "tool", name = "translate_templates" },
            messages = BuildMessages(userMessageText, corrections),
        };

        return await SendForToolUseAsync(
            request, new HashSet<string>(StringComparer.Ordinal) { "translate_templates" }, ct);
    }

    /// <summary>
    /// Builds the messages array: the stable first user turn (which, with the
    /// system blocks, forms the cached prefix), followed by any rejected attempts
    /// replayed as assistant <c>tool_use</c> + user <c>tool_result</c> pairs so a
    /// validation retry carries its feedback to Claude (WX-148).
    /// </summary>
    private static object[] BuildMessages(string userMessageText, IReadOnlyList<ReconciliationCorrection>? corrections)
    {
        var messages = new List<object> { new { role = "user", content = userMessageText } };
        if (corrections is not null)
        {
            foreach (var c in corrections)
            {
                messages.Add(new
                {
                    role = "assistant",
                    content = new object[] { new { type = "tool_use", id = c.ToolUseId, name = c.ToolName, input = c.ToolUseInput } },
                });
                messages.Add(new
                {
                    role = "user",
                    content = new object[] { new { type = "tool_result", tool_use_id = c.ToolUseId, content = c.ErrorText, is_error = true } },
                });
            }
        }
        return [.. messages];
    }

    // ── response DTOs ─────────────────────────────────────────────────────────

    private sealed class ClaudeResponse
    {
        [JsonPropertyName("content")]
        public List<ContentBlock>? Content { get; set; }

        [JsonPropertyName("usage")]
        public TokenUsageDto? Usage { get; set; }

        /// <summary>Why generation stopped; <c>"max_tokens"</c> signals a truncated, incomplete tool_use input (WX-109).</summary>
        [JsonPropertyName("stop_reason")]
        public string? StopReason { get; set; }
    }

    private sealed class ContentBlock
    {
        [JsonPropertyName("type")] public string? Type { get; set; }
        [JsonPropertyName("text")] public string? Text { get; set; }

        /// <summary>Tool-use block id when <see cref="Type"/> is <c>"tool_use"</c>; <see langword="null"/> for text blocks.</summary>
        [JsonPropertyName("id")] public string? Id { get; set; }

        /// <summary>Tool name when <see cref="Type"/> is <c>"tool_use"</c>; <see langword="null"/> for text blocks.</summary>
        [JsonPropertyName("name")] public string? Name { get; set; }

        /// <summary>Tool-use input object when <see cref="Type"/> is <c>"tool_use"</c>; default-valued for text blocks.</summary>
        [JsonPropertyName("input")] public JsonElement Input { get; set; }
    }

    private sealed class TokenUsageDto
    {
        [JsonPropertyName("input_tokens")] public int InputTokens { get; set; }
        [JsonPropertyName("output_tokens")] public int OutputTokens { get; set; }
        [JsonPropertyName("cache_creation_input_tokens")] public int CacheCreationInputTokens { get; set; }
        [JsonPropertyName("cache_read_input_tokens")] public int CacheReadInputTokens { get; set; }
    }
}