using System.Net.Http.Json;
using System.Text.Json;
using System.Text.Json.Serialization;

using WxServices.Logging;

namespace WxReport.Svc;

/// <summary>
/// Token-usage breakdown returned by the Anthropic Messages API for a single
/// request.  Cache fields are zero when no cache hit occurred or the cache
/// markers in the request did not produce a cacheable prefix.
/// </summary>
/// <param name="InputTokens">Total billed input tokens for the request (cached and uncached combined).</param>
/// <param name="OutputTokens">Output tokens generated by the model.</param>
/// <param name="CacheReadInputTokens">Input tokens served from a prior cache write (heavily discounted).</param>
/// <param name="CacheCreationInputTokens">Input tokens written to the cache by this request (one-time write cost).</param>
public sealed record TokenUsage(
    int InputTokens,
    int OutputTokens,
    int CacheReadInputTokens,
    int CacheCreationInputTokens);

/// <summary>
/// Successful result of <see cref="ClaudeClient.InvokeReconciliationAsync"/>:
/// the raw <c>tool_use.input</c> JSON returned by Claude, plus token usage.
/// Schema validation of <see cref="ToolUseInput"/> is the caller's
/// responsibility — typically by reading <c>final_snapshot</c> as a string
/// and passing it through
/// <see cref="MetarParser.Data.Entities.ForecastSnapshotBody.Deserialize"/>,
/// which enforces both shape and the precipPhenomenon-iff-non-none invariant.
/// </summary>
/// <param name="ToolName">Name of the tool Claude invoked — <c>"submit_reconciled_report"</c> to send, or <c>"skip_send"</c> for the WX-80 "not news" outcome.</param>
/// <param name="ToolUseInput">JsonElement representing the tool_use block's <c>input</c> object.</param>
/// <param name="Tokens">Token-usage metadata extracted from the response's <c>usage</c> block.</param>
/// <param name="StopReason">
/// The response's <c>stop_reason</c> (e.g. <c>"tool_use"</c>, <c>"end_turn"</c>,
/// <c>"max_tokens"</c>).  <c>"max_tokens"</c> means generation was cut at the
/// output-token cap, so <see cref="ToolUseInput"/> is a truncated partial object
/// (a trailing required field is typically missing).  The caller checks this
/// before reading fields so a truncation is reported as such rather than
/// mislabelled a missing/omitted field (WX-109).
/// </param>
public sealed record ClaudeReconciliationResult(
    string ToolName,
    JsonElement ToolUseInput,
    TokenUsage Tokens,
    string? StopReason);

/// <summary>
/// Thin wrapper around the Anthropic Messages API.  Exposes the single
/// tool-use call driving the WX-79 forecast reconciliation pass; higher-level
/// orchestration (per-recipient system-prompt construction, user-message
/// assembly, response validation) lives in <see cref="ForecastReconciler"/>.
/// </summary>
public sealed class ClaudeClient
{
    private const string MessagesEndpoint = "https://api.anthropic.com/v1/messages";
    private const string AnthropicVersion = "2023-06-01";

    // Output-token ceiling for the reconciliation call. The three artifacts
    // (a full inline-CSS HTML email_body, a final_snapshot of up to 24 six-hour
    // blocks for a six-day horizon, and a reasoning_trace) are emitted in one
    // tool_use response; on a large day they can exceed the old 8192 cap, at
    // which point Anthropic returns stop_reason "max_tokens" with a truncated
    // partial tool_use input — a trailing required field (often email_body) is
    // dropped and the pass fails. 16384 gives comfortable worst-case headroom
    // on a Sonnet-class model (which supports far more), and billing is per
    // token actually generated, not per ceiling (WX-109).
    private const int MaxOutputTokens = 16384;

    private readonly HttpClient _http;
    private readonly string _apiKey;
    private readonly string _model;
    private readonly string _personaPrefix;

    /// <summary>Initializes a new instance of <see cref="ClaudeClient"/> with the given credentials, model, and persona prefix.</summary>
    /// <param name="http">HTTP client used for all requests to the Anthropic Messages API.</param>
    /// <param name="apiKey">Anthropic API key; sent as the <c>x-api-key</c> header.</param>
    /// <param name="model">Claude model ID to use for generation (e.g. <c>"claude-sonnet-4-6"</c>).</param>
    /// <param name="personaPrefix">
    /// Author-persona text (the contents of the recipient's persona file, e.g. <c>AboutPaul.md</c>)
    /// sent as the first <c>system</c> content block on every Messages API call.
    /// </param>
    public ClaudeClient(HttpClient http, string apiKey, string model, string personaPrefix)
    {
        _http = http;
        _apiKey = apiKey;
        _model = model;
        _personaPrefix = personaPrefix;
    }

    /// <summary>
    /// Invokes Claude with tool-use enabled to perform the WX-79 forecast
    /// reconciliation pass.  Builds the three-block system prompt (persona +
    /// reconciliation guidance + per-recipient rendering rules), offers the
    /// reconciliation tool(s) per <paramref name="allowSkip"/> (forcing
    /// <c>submit_reconciled_report</c> when <see langword="false"/>, or offering
    /// it alongside <c>skip_send</c> with <c>tool_choice: any</c> when
    /// <see langword="true"/>), posts to the Anthropic Messages API with
    /// retry/backoff, and returns the selected tool's name and raw tool_use
    /// input JSON plus token-usage metadata.  Returns <see langword="null"/> on
    /// HTTP failure, on a missing or wrong-named tool_use block, or on
    /// response-parse failure.
    ///
    /// <para>
    /// Schema validation of the returned input is the caller's responsibility:
    /// the standard path is to read <c>final_snapshot</c> as a string and pass
    /// it through <see cref="MetarParser.Data.Entities.ForecastSnapshotBody.Deserialize"/>,
    /// which enforces both shape and the precipPhenomenon-iff-non-none
    /// invariant.
    /// </para>
    /// </summary>
    /// <param name="perRecipientSystemPrompt">
    /// Per-recipient rendering rules; the third (uncached) system block.
    /// Built by the caller from language, units, change-severity, and other
    /// per-call context.
    /// </param>
    /// <param name="userMessageText">
    /// User message carrying the structured payload (provisional snapshot,
    /// observation, forecast, prior snapshot, with their timestamps).
    /// </param>
    /// <param name="allowSkip">
    /// When <see langword="true"/> (unscheduled, arrival-triggered cycles), both
    /// the <c>submit_reconciled_report</c> and <c>skip_send</c> tools are offered
    /// and <c>tool_choice</c> is <c>any</c>, so Claude may decline to send.  When
    /// <see langword="false"/> (scheduled / first / startup sends), only
    /// <c>submit_reconciled_report</c> is offered and forced — those cycles are
    /// always worth sending and must never be skipped.
    /// </param>
    /// <param name="ct">Cancellation token propagated to the HTTP request so that host shutdown aborts an in-flight API call.</param>
    /// <returns>The chosen tool's name and input plus token usage on success; <see langword="null"/> on transport, schema, or parse failure.</returns>
    /// <sideeffects>Makes an HTTP POST request to the Anthropic Messages API. Writes error log entries on failure.</sideeffects>
    public async Task<ClaudeReconciliationResult?> InvokeReconciliationAsync(
        string perRecipientSystemPrompt,
        string userMessageText,
        bool allowSkip,
        CancellationToken ct = default)
    {
        // Arrival-triggered cycles offer Claude the invalidation gate (submit OR
        // skip, tool_choice "any"); scheduled/first/startup cycles force the
        // submit tool so a guaranteed send can never be skipped.
        var tools = allowSkip
            ? new[] { ReconcilerPrompts.BuildSubmitReconciledReportTool(), ReconcilerPrompts.BuildSkipSendTool() }
            : new[] { ReconcilerPrompts.BuildSubmitReconciledReportTool() };
        object toolChoice = allowSkip
            ? new { type = "any" }
            : new { type = "tool", name = "submit_reconciled_report" };

        var request = new
        {
            model = _model,
            max_tokens = MaxOutputTokens,
            system = new object[]
            {
                new { type = "text", text = _personaPrefix },
                new
                {
                    type = "text",
                    text = ReconcilerPrompts.ReconciliationGuidanceText,
                    cache_control = new { type = "ephemeral" },
                },
                new { type = "text", text = perRecipientSystemPrompt },
            },
            tools,
            tool_choice = toolChoice,
            messages = new[]
            {
                new { role = "user", content = userMessageText },
            },
        };

        const int maxAttempts = 3;
        HttpResponseMessage resp;

        for (int attempt = 1; ; attempt++)
        {
            using var req = new HttpRequestMessage(HttpMethod.Post, MessagesEndpoint);
            req.Headers.Add("x-api-key", _apiKey);
            req.Headers.Add("anthropic-version", AnthropicVersion);
            req.Content = JsonContent.Create(request);

            try
            {
                resp = await _http.SendAsync(req, ct);
            }
            catch (OperationCanceledException) when (ct.IsCancellationRequested)
            {
                // Genuine host-shutdown cancellation — abort promptly, do not retry.
                Logger.Info("Claude API request canceled by host shutdown.");
                return null;
            }
            catch (Exception ex) when (attempt < maxAttempts && ex is HttpRequestException)
            {
                // Connection-level failures are transient — retry with backoff.
                Logger.Warn($"Claude API request failed (attempt {attempt}/{maxAttempts}): {ex.Message}");
                await Task.Delay(TimeSpan.FromSeconds(attempt * 2), ct);
                continue;
            }
            catch (Exception ex)
            {
                // Includes an HttpClient.Timeout (TaskCanceledException, ct not
                // signalled).  WX-100: the dedicated Claude client's generous timeout
                // makes timeouts rare, and a timeout at that ceiling signals a real
                // stall, not a blip — so fail the pass and recover next cycle rather
                // than retrying a multi-minute call up to 3x (code-review finding).
                Logger.Error($"Claude API request failed: {ex}");
                return null;
            }

            var statusCode = (int)resp.StatusCode;
            if (resp.IsSuccessStatusCode) break;

            var body = await resp.Content.ReadAsStringAsync();
            resp.Dispose();

            if (attempt < maxAttempts && statusCode is 429 or 529 or >= 500)
            {
                Logger.Warn($"Claude API returned {statusCode} (attempt {attempt}/{maxAttempts}): {body}");
                await Task.Delay(TimeSpan.FromSeconds(attempt * 2), ct);
                continue;
            }

            Logger.Error($"Claude API returned {statusCode}: {body}");
            return null;
        }

        using (resp)
        {
            ClaudeResponse? parsed;
            try
            {
                parsed = await resp.Content.ReadFromJsonAsync<ClaudeResponse>();
            }
            catch (Exception ex)
            {
                Logger.Error($"Failed to parse Claude API response: {ex.Message}");
                return null;
            }

            // Enforce the allowSkip contract on the way back: a valid reconciliation
            // response is exactly one tool_use block whose name is permitted for this
            // cycle. submit_reconciled_report is always permitted; skip_send only when
            // allowSkip is true (the cycle offered it via toolChoice above). Anything
            // else — zero blocks, more than one block (a self-contradictory submit+skip
            // would otherwise be resolved by arbitrary ordering), or an un-offered tool
            // — is malformed output: reject it here at the API boundary (return null ->
            // caller's Failure path) rather than guess. This keeps the choice
            // deterministic and makes ClaudeReconciliationResult.ToolName always a tool
            // that was actually permitted for this cycle.
            var toolUseBlocks = parsed?.Content?.Where(c => c.Type == "tool_use").ToList();

            if (toolUseBlocks is not { Count: 1 })
            {
                // Include stop_reason: a "max_tokens" truncation can cut generation
                // before any tool_use block is emitted, which would otherwise read as
                // a baffling "0 tool_use blocks" rather than the token-cap hit it is
                // (WX-109). The common truncation case — one block with a partial
                // input — is handled downstream in ForecastReconciler via StopReason.
                Logger.Error($"Claude response had {toolUseBlocks?.Count ?? 0} tool_use block(s); expected exactly 1 (allowSkip={allowSkip}, stop_reason={parsed?.StopReason ?? "null"}).");
                return null;
            }

            var toolName = toolUseBlocks[0].Name;
            if (toolName is not ("submit_reconciled_report" or "skip_send")
                || (toolName == "skip_send" && !allowSkip))
            {
                Logger.Error($"Claude response tool_use '{toolName}' is not permitted for allowSkip={allowSkip}.");
                return null;
            }

            var toolUse = toolUseBlocks[0];

            var usage = parsed?.Usage;
            var tokens = new TokenUsage(
                InputTokens: usage?.InputTokens ?? 0,
                OutputTokens: usage?.OutputTokens ?? 0,
                CacheReadInputTokens: usage?.CacheReadInputTokens ?? 0,
                CacheCreationInputTokens: usage?.CacheCreationInputTokens ?? 0);

            return new ClaudeReconciliationResult(toolName, toolUse.Input, tokens, parsed?.StopReason);
        }
    }

    // ── response DTOs ─────────────────────────────────────────────────────────

    private sealed class ClaudeResponse
    {
        [JsonPropertyName("content")]
        public List<ContentBlock>? Content { get; set; }

        [JsonPropertyName("usage")]
        public TokenUsageDto? Usage { get; set; }

        /// <summary>Why generation stopped; <c>"max_tokens"</c> signals a truncated, incomplete tool_use input (WX-109).</summary>
        [JsonPropertyName("stop_reason")]
        public string? StopReason { get; set; }
    }

    private sealed class ContentBlock
    {
        [JsonPropertyName("type")] public string? Type { get; set; }
        [JsonPropertyName("text")] public string? Text { get; set; }

        /// <summary>Tool name when <see cref="Type"/> is <c>"tool_use"</c>; <see langword="null"/> for text blocks.</summary>
        [JsonPropertyName("name")] public string? Name { get; set; }

        /// <summary>Tool-use input object when <see cref="Type"/> is <c>"tool_use"</c>; default-valued for text blocks.</summary>
        [JsonPropertyName("input")] public JsonElement Input { get; set; }
    }

    private sealed class TokenUsageDto
    {
        [JsonPropertyName("input_tokens")] public int InputTokens { get; set; }
        [JsonPropertyName("output_tokens")] public int OutputTokens { get; set; }
        [JsonPropertyName("cache_creation_input_tokens")] public int CacheCreationInputTokens { get; set; }
        [JsonPropertyName("cache_read_input_tokens")] public int CacheReadInputTokens { get; set; }
    }
}