// <auto-generated />
using System;
using MetarParser.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MetarParser.Data.Migrations
{
    [DbContext(typeof(WeatherDataContext))]
    [Migration("20260704172609_AddNoonMidnightTokens")]
    partial class AddNoonMidnightTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MetarParser.Data.Entities.CommittedSend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ForecastSnapshotId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDiagnostic")
                        .HasColumnType("bit");

                    b.Property<string>("ReasoningTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SchemaVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("StructuredReport")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ForecastSnapshotId");

                    b.HasIndex("RecipientId", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_CommittedSends_Recipient_CreatedAt");

                    b.ToTable("CommittedSends", (string)null);
                });

            modelBuilder.Entity("MetarParser.Data.Entities.ForecastSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("SchemaVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<string>("StationIcao")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nchar(4)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("StationIcao", "GeneratedAtUtc")
                        .IsUnique()
                        .HasDatabaseName("UX_ForecastSnapshots_Station_GeneratedAt");

                    b.ToTable("ForecastSnapshots", (string)null);
                });

            modelBuilder.Entity("MetarParser.Data.Entities.GfsGridPoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<float?>("CapeJKg")
                        .HasColumnType("real");

                    b.Property<float?>("DwpC")
                        .HasColumnType("real");

                    b.Property<int>("ForecastHour")
                        .HasColumnType("int");

                    b.Property<float>("Lat")
                        .HasColumnType("real");

                    b.Property<float>("Lon")
                        .HasColumnType("real");

                    b.Property<DateTime>("ModelRunUtc")
                        .HasColumnType("datetime2");

                    b.Property<float?>("PRateKgM2s")
                        .HasColumnType("real");

                    b.Property<float?>("PrMslPa")
                        .HasColumnType("real");

                    b.Property<float?>("TcdcPct")
                        .HasColumnType("real");

                    b.Property<float?>("TmpC")
                        .HasColumnType("real");

                    b.Property<float?>("UGrdMs")
                        .HasColumnType("real");

                    b.Property<float?>("VGrdMs")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ModelRunUtc", "ForecastHour")
                        .HasDatabaseName("IX_GfsGrid_Run_Hour");

                    b.HasIndex("ModelRunUtc", "ForecastHour", "Lat", "Lon")
                        .IsUnique()
                        .HasDatabaseName("UX_GfsGrid_Run_Hour_LatLon");

                    b.ToTable("GfsGrid", (string)null);
                });

            modelBuilder.Entity("MetarParser.Data.Entities.GfsModelRun", b =>
                {
                    b.Property<DateTime>("ModelRunUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.HasKey("ModelRunUtc");

                    b.ToTable("GfsModelRuns", (string)null);
                });

            modelBuilder.Entity("MetarParser.Data.Entities.GlobalSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaudeApiKey")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GeminiApiKey")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SmtpFromAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SmtpPassword")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SmtpUsername")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("GlobalSettings", (string)null);
                });

            modelBuilder.Entity("MetarParser.Data.Entities.Language", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CultureName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("GeneratedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("GenerationError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("IsoCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Languages_IsoCode");

                    b.ToTable("Languages", (string)null);
                });

            modelBuilder.Entity("MetarParser.Data.Entities.LanguageTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ContextInfo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ContextKind")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Phrase")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Representable")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId", "Token")
                        .IsUnique()
                        .HasDatabaseName("UX_LanguageTemplates_LanguageId_Token");

                    b.ToTable("LanguageTemplates", (string)null);
                });

            modelBuilder.Entity("MetarParser.Data.Entities.Locality", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double?>("CentroidLat")
                        .HasColumnType("float");

                    b.Property<double?>("CentroidLon")
                        .HasColumnType("float");

                    b.Property<string>("MetarIcao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ScheduledSendHours")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TafIcao")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Localities_Name");

                    b.ToTable("Localities", (string)null);
                });

            modelBuilder.Entity("MetarParser.Data.Entities.LocalityState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("LastClaudeInputHash")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastDegradedInputHash")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastMetarIcao")
                        .HasMaxLength(4)
                        .HasColumnType("nchar(4)")
                        .IsFixedLength();

                    b.Property<DateTime?>("LastScheduledSentUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastSentInputHash")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("LastUnscheduledSentUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("LocalityId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LocalityId")
                        .IsUnique()
                        .HasDatabaseName("UX_LocalityStates_LocalityId");

                    b.ToTable("LocalityStates", (string)null);
                });

            modelBuilder.Entity("MetarParser.Data.Entities.MetarRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("AirTemperatureCelsius")
                        .HasColumnType("float");

                    b.Property<string>("AltimeterUnit")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<double?>("AltimeterValue")
                        .HasColumnType("float");

                    b.Property<double?>("DewPointCelsius")
                        .HasColumnType("float");

                    b.Property<bool>("IsAuto")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCorrection")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ObservationUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RawReport")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("RawRunwayVisualRange")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RawSkyConditions")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RawWeatherPhenomena")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ReceivedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("StationIcao")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nchar(4)")
                        .IsFixedLength();

                    b.Property<bool>("VisibilityCavok")
                        .HasColumnType("bit");

                    b.Property<bool>("VisibilityLessThan")
                        .HasColumnType("bit");

                    b.Property<int?>("VisibilityM")
                        .HasColumnType("int");

                    b.Property<double?>("VisibilityStatuteMiles")
                        .HasColumnType("float");

                    b.Property<int?>("WindDirection")
                        .HasColumnType("int");

                    b.Property<int?>("WindGust")
                        .HasColumnType("int");

                    b.Property<bool>("WindIsVariable")
                        .HasColumnType("bit");

                    b.Property<int?>("WindSpeed")
                        .HasColumnType("int");

                    b.Property<string>("WindUnit")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int?>("WindVariableFrom")
                        .HasColumnType("int");

                    b.Property<int?>("WindVariableTo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StationIcao")
                        .HasDatabaseName("IX_Metars_StationIcao");

                    b.HasIndex("StationIcao", "ObservationUtc", "ReportType")
                        .IsUnique()
                        .HasDatabaseName("UX_Metars_Station_Time_Type");

                    b.ToTable("Metars", (string)null);
                });

            modelBuilder.Entity("MetarParser.Data.Entities.MetarRunwayVisualRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AboveMaximum")
                        .HasColumnType("bit");

                    b.Property<bool>("BelowMinimum")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxMeters")
                        .HasColumnType("int");

                    b.Property<int?>("MeanMeters")
                        .HasColumnType("int");

                    b.Property<int>("MetarId")
                        .HasColumnType("int");

                    b.Property<int?>("MinMeters")
                        .HasColumnType("int");

                    b.Property<string>("Runway")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Trend")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.HasIndex("MetarId");

                    b.ToTable("MetarRunwayVisualRanges", (string)null);
                });

            modelBuilder.Entity("MetarParser.Data.Entities.MetarSkyCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CloudType")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Cover")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int?>("HeightFeet")
                        .HasColumnType("int");

                    b.Property<bool>("IsVerticalVisibility")
                        .HasColumnType("bit");

                    b.Property<int>("MetarId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MetarId");

                    b.ToTable("MetarSkyConditions", (string)null);
                });

            modelBuilder.Entity("MetarParser.Data.Entities.MetarWeatherPhenomenon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descriptor")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Intensity")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("MetarId")
                        .HasColumnType("int");

                    b.Property<string>("Obscuration")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("OtherPhenomenon")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("PhenomenonKind")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Precipitation")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MetarId");

                    b.ToTable("MetarWeatherPhenomena", (string)null);
                });

            modelBuilder.Entity("MetarParser.Data.Entities.PromptGlossaryToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("UX_PromptGlossaryTokens_Token");

                    b.ToTable("PromptGlossaryTokens", (string)null);
                });

            modelBuilder.Entity("MetarParser.Data.Entities.QaRerunRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResultStamp")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("Id");

                    b.HasIndex("IsoCode")
                        .IsUnique()
                        .HasDatabaseName("UX_QaRerunRequests_IsoCode");

                    b.ToTable("QaRerunRequests", (string)null);
                });

            modelBuilder.Entity("MetarParser.Data.Entities.Recipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<long?>("LocalityId")
                        .HasColumnType("bigint");

                    b.Property<string>("LocalityName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("MetarIcao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NumberFormat")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PrecipUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PressureUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RecipientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ScheduledSendHours")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TafIcao")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TempUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WindSpeedUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LocalityId");

                    b.HasIndex("RecipientId")
                        .IsUnique()
                        .HasDatabaseName("UX_Recipients_RecipientId");

                    b.ToTable("Recipients", (string)null);
                });

            modelBuilder.Entity("MetarParser.Data.Entities.RecipientState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LastClaudeInputHash")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastMetarIcao")
                        .HasMaxLength(4)
                        .HasColumnType("nchar(4)")
                        .IsFixedLength();

                    b.Property<DateTime?>("LastScheduledSentUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastSentInputHash")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("LastUnscheduledSentUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecipientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId")
                        .IsUnique()
                        .HasDatabaseName("UX_RecipientStates_RecipientId");

                    b.ToTable("RecipientStates", (string)null);
                });

            modelBuilder.Entity("MetarParser.Data.Entities.TafChangePeriodRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("RawSkyConditions")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RawWeather")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("TafId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ValidFromUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidToUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("VisibilityCavok")
                        .HasColumnType("bit");

                    b.Property<bool>("VisibilityLessThan")
                        .HasColumnType("bit");

                    b.Property<int?>("VisibilityM")
                        .HasColumnType("int");

                    b.Property<double?>("VisibilityStatuteMiles")
                        .HasColumnType("float");

                    b.Property<int?>("WindDirection")
                        .HasColumnType("int");

                    b.Property<int?>("WindGust")
                        .HasColumnType("int");

                    b.Property<bool>("WindIsVariable")
                        .HasColumnType("bit");

                    b.Property<int?>("WindSpeed")
                        .HasColumnType("int");

                    b.Property<string>("WindUnit")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    b.HasIndex("TafId");

                    b.ToTable("TafChangePeriods", (string)null);
                });

            modelBuilder.Entity("MetarParser.Data.Entities.TafChangePeriodSky", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CloudType")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Cover")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int?>("HeightFeet")
                        .HasColumnType("int");

                    b.Property<bool>("IsVerticalVisibility")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("TafChangePeriodId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TafChangePeriodId");

                    b.ToTable("TafChangePeriodSkyConditions", (string)null);
                });

            modelBuilder.Entity("MetarParser.Data.Entities.TafChangePeriodWeather", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descriptor")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Intensity")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Obscuration")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("OtherPhenomenon")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Precipitation")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("TafChangePeriodId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TafChangePeriodId");

                    b.ToTable("TafChangePeriodWeatherPhenomena", (string)null);
                });

            modelBuilder.Entity("MetarParser.Data.Entities.TafRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("IssuanceUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RawReport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReceivedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("StationIcao")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nchar(4)")
                        .IsFixedLength();

                    b.Property<DateTime>("ValidFromUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidToUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StationIcao")
                        .HasDatabaseName("IX_Tafs_StationIcao");

                    b.HasIndex("StationIcao", "IssuanceUtc", "ReportType")
                        .IsUnique()
                        .HasDatabaseName("UX_Tafs_Station_Issuance_Type");

                    b.ToTable("Tafs", (string)null);
                });

            modelBuilder.Entity("MetarParser.Data.Entities.WxStation", b =>
                {
                    b.Property<string>("IcaoId")
                        .HasMaxLength(4)
                        .HasColumnType("nchar(4)")
                        .IsFixedLength();

                    b.Property<bool?>("AlwaysFetchDirect")
                        .HasColumnType("bit");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CountryAbbr")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .IsFixedLength();

                    b.Property<double?>("ElevationFt")
                        .HasColumnType("float");

                    b.Property<double?>("Lat")
                        .HasColumnType("float");

                    b.Property<double?>("Lon")
                        .HasColumnType("float");

                    b.Property<string>("Municipality")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RegionAbbr")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RegionCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IcaoId");

                    b.ToTable("WxStations", (string)null);
                });

            modelBuilder.Entity("MetarParser.Data.Entities.CommittedSend", b =>
                {
                    b.HasOne("MetarParser.Data.Entities.ForecastSnapshot", "ForecastSnapshot")
                        .WithMany()
                        .HasForeignKey("ForecastSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ForecastSnapshot");
                });

            modelBuilder.Entity("MetarParser.Data.Entities.LanguageTemplate", b =>
                {
                    b.HasOne("MetarParser.Data.Entities.Language", "Language")
                        .WithMany("Templates")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("MetarParser.Data.Entities.LocalityState", b =>
                {
                    b.HasOne("MetarParser.Data.Entities.Locality", "Locality")
                        .WithMany()
                        .HasForeignKey("LocalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Locality");
                });

            modelBuilder.Entity("MetarParser.Data.Entities.MetarRunwayVisualRange", b =>
                {
                    b.HasOne("MetarParser.Data.Entities.MetarRecord", "Metar")
                        .WithMany("RunwayVisualRanges")
                        .HasForeignKey("MetarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metar");
                });

            modelBuilder.Entity("MetarParser.Data.Entities.MetarSkyCondition", b =>
                {
                    b.HasOne("MetarParser.Data.Entities.MetarRecord", "Metar")
                        .WithMany("SkyConditions")
                        .HasForeignKey("MetarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metar");
                });

            modelBuilder.Entity("MetarParser.Data.Entities.MetarWeatherPhenomenon", b =>
                {
                    b.HasOne("MetarParser.Data.Entities.MetarRecord", "Metar")
                        .WithMany("WeatherPhenomena")
                        .HasForeignKey("MetarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metar");
                });

            modelBuilder.Entity("MetarParser.Data.Entities.Recipient", b =>
                {
                    b.HasOne("MetarParser.Data.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MetarParser.Data.Entities.Locality", "Locality")
                        .WithMany()
                        .HasForeignKey("LocalityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Language");

                    b.Navigation("Locality");
                });

            modelBuilder.Entity("MetarParser.Data.Entities.TafChangePeriodRecord", b =>
                {
                    b.HasOne("MetarParser.Data.Entities.TafRecord", "Taf")
                        .WithMany("ChangePeriods")
                        .HasForeignKey("TafId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Taf");
                });

            modelBuilder.Entity("MetarParser.Data.Entities.TafChangePeriodSky", b =>
                {
                    b.HasOne("MetarParser.Data.Entities.TafChangePeriodRecord", "ChangePeriod")
                        .WithMany("SkyConditions")
                        .HasForeignKey("TafChangePeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangePeriod");
                });

            modelBuilder.Entity("MetarParser.Data.Entities.TafChangePeriodWeather", b =>
                {
                    b.HasOne("MetarParser.Data.Entities.TafChangePeriodRecord", "ChangePeriod")
                        .WithMany("WeatherPhenomena")
                        .HasForeignKey("TafChangePeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangePeriod");
                });

            modelBuilder.Entity("MetarParser.Data.Entities.Language", b =>
                {
                    b.Navigation("Templates");
                });

            modelBuilder.Entity("MetarParser.Data.Entities.MetarRecord", b =>
                {
                    b.Navigation("RunwayVisualRanges");

                    b.Navigation("SkyConditions");

                    b.Navigation("WeatherPhenomena");
                });

            modelBuilder.Entity("MetarParser.Data.Entities.TafChangePeriodRecord", b =>
                {
                    b.Navigation("SkyConditions");

                    b.Navigation("WeatherPhenomena");
                });

            modelBuilder.Entity("MetarParser.Data.Entities.TafRecord", b =>
                {
                    b.Navigation("ChangePeriods");
                });
#pragma warning restore 612, 618
        }
    }
}
